lukascane/Virtual_Bookshell

Models/BookSchema.js, Models/ReviewSchema.js, Models/UserSchema.js, Routes/bookRoutes.js, notes/ideas/structure/database-structure.md
**Created Schema for project**
- user
- book collections
- review
=> created 3 schemas , finished

Controllers/booksController.js, Controllers/reviewController.js, Controllers/userControllers.js, Models/BookSchema.js, Models/ReviewSchema.js, Routes/bookRoutes.js, Routes/reviewRoutes.js, Routes/userRoutes.js, server.js
Created routes and controllers
=> Added routes and controllers

client/src/App.js, client/src/assets/scss/_formSearch.scss, client/src/assets/scss/main.scss, client/src/components/Form/SearchForm.jsx
=> Form for search

client/src/context/booksContextApi/BookContext.js, client/src/context/booksContextApi/BooksProvider.js
=> Context api setup

client/src/App.js, client/src/assets/scss/_commentReview.scss, client/src/assets/scss/_reviewModal.scss, client/src/assets/scss/main.scss, client/src/components/Modals/CommentReview.jsx, client/src/components/Modals/ReviewModal.jsx
Modal for review and comment + Comment component
=> reviewModal+Comment

notes/ideas/structure/userAuth.md
Wrote some structure in userAuth.md
=> Did userAuth structure

client/src/App.js, client/src/assets/scss/_loginForm.scss, client/src/assets/scss/_profileCard.scss, client/src/assets/scss/main.scss, client/src/components/Form/LoginForm.jsx, client/src/components/Form/SignUpForm.jsx, client/src/components/ProfileComponents/EditProfileForm.jsx, client/src/components/ProfileComponents/ProfileCard.jsx
Bunch of forms and profile components
=> AllForms+ProfileComponent

client/src/App.js, client/src/assets/scss/_listcard.scss, client/src/assets/scss/main.scss, client/src/components/Card/Card.jsx, client/src/components/Card/ListCardToRead.jsx
last components done - list to read - list read
=> listsCards

client/package-lock.json, client/package.json, client/src/App.js, client/src/components/Card/Card.jsx, client/src/components/Form/SearchForm.jsx, client/src/components/Wrapper/CardWrapper.jsx, client/src/components/wrapper/CardWrapper.jsx, client/src/context/booksContextApi/BookContext.js, client/src/context/booksContextApi/BooksProvider.js, client/src/hoc/MainRouter.jsx, client/src/services/bookApi/searchTitleAuthApi.js, client/src/services/bookApi/sendBookInfoApi.js, client/src/util/sanitizeBookData.js, client/src/util/searchAxiosInstance.js
Cleaned App.js and implemented context api
=> Fetch api for card props

client/src/context/booksContextApi/BookActions.js, client/src/context/booksContextApi/BookContextR.js, client/src/context/booksContextApi/BookProviderR.js, client/src/context/booksContextApi/BookReducer.js
=> Setup reducer

client/src/assets/scss/_body.scss, client/src/assets/scss/_homeBanner.scss, client/src/pages/ReadList/ReadList.jsx
Landing debugged start to make list W.
=> LandingDebugged

client/src/assets/scss/_body.scss, client/src/assets/scss/_bookModal.scss, client/src/assets/scss/_listcard.scss, client/src/assets/scss/_navbar.scss, client/src/assets/scss/_readListsWiew.scss, client/src/assets/scss/_reviewModal.scss, client/src/assets/scss/main.scss, client/src/components/Card/ListCard.jsx, client/src/components/Modals/BookModal.jsx, client/src/components/Modals/ReviewModal.jsx, client/src/components/Navbar/NavBarGuest.jsx, client/src/components/Navbar/NavBarLoggedIn.jsx, client/src/hoc/MainRouter.jsx, client/src/pages/ReadList/ToReadList.jsx, notes/sprints/07-14.02.2022.md
=> List wiews

client/src/components/Card/MiniCard.jsx, client/src/components/Wrapper/MiniCardWrapper.jsx, client/src/pages/SearchBooks/SearchBooks.jsx, client/src/services/bookApi/searchTitleAuthApi.js
Added miniCardWrapper component
=> Setup miniCardWrapper

client/src/components/Modals/BookModal.jsx, client/src/components/Modals/CommentReview.jsx, client/src/components/Modals/ErrorModal.jsx, client/src/components/Modals/ReviewModal.jsx, client/src/hoc/MainRouter.jsx
Added browserrouter to MainRouter.jsx
=> Browser router

client/src/components/Navbar/NavBarGuest.jsx, client/src/components/Navbar/NavBarLoggedIn.jsx, client/src/hoc/MainRouter.jsx
=> navbarlinks created

client/src/components/Form/LoginForm.jsx, client/src/components/Form/SignUpForm.jsx
Connected registration & login to database
=> Connected registration & login to database

notes/sprints/07-11.02.2022.md, notes/sprints/14-18.02.2022.md
Updated notes: sprint 14.-18.02.2022.md
=> Added sprint 14-18.02.2022

Controllers/userControllers.js, Middleware/roleManager.js, Models/UserSchema.js, Routes/userRoutes.js, passport-config.js, server.js
=> rolemanager

client/src/components/Form/SearchForm.jsx, client/src/components/ParagraphInfo/ParagraphInfo.jsx
=> ParagraphDone

client/src/components/Form/LoginForm.jsx, client/src/components/Navbar/NavBarGuest.jsx, client/src/components/Navbar/NavBarLoggedIn.jsx, client/src/components/Wrapper/NavbarWrapper.jsx, client/src/context/booksContextApi/BooksProvider.js, client/src/hoc/MainRouter.jsx, client/src/pages/Login/Login.jsx
Implemented logout function.
Implemented navbarWrapper
=> Implemented logout & NavbarWrapper

client/src/services/bookApi/searchTitleAuthApi.js
Updated dummy queries for searchbooks
=> Updated dummy queries for searchbooks

client/src/assets/scss/_formSearch.scss, client/src/assets/scss/_navbar.scss, client/src/assets/scss/_profileCard.scss, client/src/components/Form/SignUpForm.jsx, client/src/components/Navbar/NavBarGuest.jsx, client/src/components/Navbar/NavBarLoggedIn.jsx, client/src/components/ParagraphInfo/AlertPasswordminimum.jsx, client/src/components/ParagraphInfo/AlertProfileDeleted.jsx, client/src/components/ParagraphInfo/AlertSureToDelete.jsx, client/src/components/ProfileComponents/AvatarSelector.jsx, client/src/components/ProfileComponents/ProfileCard.jsx, client/src/context/AlertProvider.js, client/src/pages/Profile/Profile.jsx, client/src/pages/Registration/Registration.jsx
=> formAlertFuncDone

client/src/components/Card/ListCard.jsx, client/src/components/Card/ListCardToRead.jsx, client/src/context/booksContextApi/BooksProvider.js
Implemented reading status to button on ListCard and ToReadListCard
=> Reading status

client/src/components/Card/Card.jsx, client/src/components/Card/ListCard.jsx, client/src/components/Card/ListCardToRead.jsx, client/src/components/Modals/BookModal.jsx, client/src/components/Modals/ReviewModal.jsx, client/src/context/ModalProvider.js
call for Review modal in 4 places: Card ListCard ListCardToRead BookModal
=> reviewModalCall

client/src/components/Card/Card.jsx, client/src/context/booksContextApi/BooksProvider.js
Added first readingStatus to send for database
=> Send reading status

client/src/components/Card/Card.jsx, client/src/components/Modals/BookModal.jsx, client/src/context/booksContextApi/BooksProvider.js
Book info and reading status --> send to database from card and modal
=> Send info and status from Modal and Card

client/src/assets/scss/_formSearch.scss, client/src/components/Form/SearchForm.jsx, client/src/components/Modals/BookModal.jsx, client/src/components/Modals/ReviewModal.jsx, client/src/components/ParagraphInfo/ParagraphInfo.jsx, client/src/components/Wrapper/CardWrapper.jsx, client/src/context/AlertProvider.js, client/src/context/booksContextApi/BooksProvider.js, client/src/pages/SearchBooks/SearchBooks.jsx
onChange issue + search for "author" alert Done
=> onChangeDone

client/src/components/Card/ListCard.jsx, client/src/components/Card/ListCardToRead.jsx, client/src/components/Wrapper/ListReadWrapper.jsx, client/src/components/Wrapper/ListToReadWrapper.jsx, client/src/context/booksContextApi/BooksProvider.js
Correct lists are now rendered
=> Render correct list

server.js
=> Removed root hello world
